### ISSUE TITLE
Docker-compose up gives me error

### ISSUE THREAD

**Issue by CedCannes** [dunglas/symfony-docker#101]
I have just installed to test this environment following the documentation but it brings me an error.
I did :

`docker system prune -a`

`git clone git@github.com:dunglas/symfony-docker.git`

`cd symfony-docker`

`docker-compose up`

`2021/01/05 15:29:43 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/dunglas/mercure/caddy@main 
go: downloading github.com/dunglas/mercure/caddy v0.0.0-20210105003949-86b584892268
go: github.com/dunglas/mercure/caddy main => v0.0.0-20210105003949-86b584892268
go get: github.com/dunglas/mercure/caddy@v0.0.0-20210105003949-86b584892268 requires
	github.com/dunglas/mercure@v0.11.0: reading github.com/dunglas/mercure/go.mod at revision v0.11.0: unknown revision v0.11.0
2021/01/05 15:29:45 [FATAL] exit status 1
ERROR: Service 'caddy' failed to build: The command '/bin/sh -c xcaddy build 	--with github.com/dunglas/mercure@main 	--with github.com/dunglas/mercure/caddy@main 	--with github.com/dunglas/vulcain/caddy' returned a non-zero code: 1`

**Comment by comemanu** [comment]
Same issue since recently.
I can't build anymore.

It seems to be the same issue as on the api-platform repo : https://github.com/api-platform/api-platform/issues/1746
There is a PR that needs to be merged on the api-platform repo. i hope it will be fixed here too

**Comment by dunglas** [comment]
Fixed by the release of Mercure 0.11 RC 2.

**Comment by ylandsman** [comment]
still crashing for me error message is
Service 'caddy' failed to build : The command '/bin/sh -c xcaddy build     --with github.com/dunglas/mercure/caddy     --with github.com/dunglas/vulcain/caddy' returned a non-zero code: 1

**Comment by dunglas** [comment]
This looks like a network issue on your side.

**Comment by ylandsman** [comment]
Any suggestions for how to troubleshoot this?

Yehuda Landsman

**Comment by silverbackdan** [comment]
This is more of just a note as I try to keep an eye on this repo.

API Platform uses
```
RUN xcaddy build \
    --with github.com/dunglas/mercure/caddy \
    --with github.com/dunglas/vulcain/caddy
```
https://github.com/api-platform/api-platform/blob/main/api/Dockerfile#L116

This is working for me. I haven't tried this repo in a while but I keep an eye on the issues raised.

There may be a very good reason for it but this repo is using is a bit different:
```
RUN xcaddy build \
	--with github.com/dunglas/mercure@main \
	--with github.com/dunglas/mercure/caddy@main \
	--with github.com/dunglas/vulcain/caddy
```
https://github.com/dunglas/symfony-docker/blob/main/Dockerfile#L112

Try using the API Platform adjustment maybe?
